# -*- coding: utf-8 -*-
"""Preprocessing_1_ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QSJ9SdYAH5p-5VZJ7YvHLD_L12XgXnDq
"""

!pip install gdown

!gdown --id '1gL1j0jKh48bR0V0jsjfejkrYQKsZ6Itf'

import pandas as pd
df1 = pd.read_excel('dataset_Google-Maps-Reviews-Scraper_Sumedang.xlsx')

df1

!gdown --id '12kZFTi-WqsccKUBKKSn3Zu_9Bz0_twwX'

import pandas as pd
df2 = pd.read_excel('dataset_Google-Maps-Reviews-Scraper_Bandung.xlsx')

df2

!gdown --id '17GPTiyxBJ3gKyVYWRv4a49iH9OTFrcj4'

import pandas as pd
df3 = pd.read_excel('dataset_Google-Maps-Reviews-Scraper_Tasikmalaya.xlsx')

df3

all_df = pd.concat([df1, df2, df3])

all_df

mask = ~all_df['textTranslated'].isnull()
all_df.loc[mask, 'text'] = all_df.loc[mask, 'textTranslated']
new_df = all_df.drop(columns='textTranslated')
new_dfs = new_df.dropna(subset=['text'])

new_dfs

new_dfs.to_excel('review.xlsx')
files.download('review.xlsx')