# -*- coding: utf-8 -*-
"""Preprocessing_2_ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d8xq31cKoL6UJG9skY418Yo-RTjMi-uJ
"""

!pip install gdown

!gdown --id '1LgI2Kh4XfwCf_9FtHRS51nmdMx0sfvhd'

import pandas as pd
df = pd.read_excel('review.xlsx')

df

df['title'].value_counts()

import string
import numpy as np

# Fungsi untuk menghapus tanda baca
def remove_punctuation(text):
    # Pastikan teks bukan None dan bukan NaN
    if text is not None and not pd.isnull(text):
        punctuationfree = "".join([i for i in text if i not in string.punctuation])
        return punctuationfree
    else:
        return None

# Simpan teks yang sudah dibersihkan dari tanda baca
df['clean_msg'] = df['text'].apply(lambda x: remove_punctuation(x))

df.head()

# Fungsi untuk mengubah teks menjadi huruf kecil
def to_lower(text):
    if text is not None and not pd.isnull(text):
        return text.lower()
    else:
        return None

# Ubah teks menjadi huruf kecil
df['msg_lower'] = df['clean_msg'].apply(lambda x: to_lower(x))

import re

# Fungsi untuk tokenisasi
def tokenization(text):
    if text is not None and not pd.isnull(text):
        tokens = re.split('\\W+', text)
        return tokens
    else:
        return None

# Terapkan fungsi ke kolom
df['msg_tokenied'] = df['msg_lower'].apply(lambda x: tokenization(x))

print(df.head(10))